### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by ericdai** [yourenyouyu/serialporthelper#1]
![image](https://cloud.githubusercontent.com/assets/1776435/21079922/d1ac3f1e-bfdb-11e6-9cd9-ace0009da411.png)
node 7.21 ，windows10 ，编译失败

**Comment by yourenyouyu** [comment]
使用node v0.10.21 我用的serialport包是 2.0.6的 它不支持node7的。过阶段我会用node7重写下的
